### ISSUE TITLE
🚨 🚑  Can not vercel build (following description is error message)

### ISSUE THREAD

**Issue by yuseok-kim-edushare** [Spharos-Academy-5-Team-of-YuSeokKim/Front_Client_Side_App#35]
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[2]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[3]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css': No serializer registered for PostCSSSyntaxError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> PostCSSSyntaxError
Failed to compile.

./src/app/globals.css:5:1
Syntax error: C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css Unknown word

  3 | @tailwind utilities;
  4 | 
> 5 | <<<<<<< HEAD
    | ^
  6 | /* body {
  7 |   height: 100%;

./src/app/globals.css
Syntax error: C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css Unknown word (5:1)

  3 | @tailwind utilities;
  4 | 
> 5 | <<<<<<< HEAD
    | ^
  6 | /* body {
  7 |   height: 100%;

    at tryRunOrWebpackError (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:312989)
    at __webpack_require_module__ (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131165)
    at __nested_webpack_require_153728__ (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:130607)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131454
    at symbolIterator (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\neo-async\async.js:1:14444)
    at done (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\neo-async\async.js:1:14824)
    at Hook.eval [as callAsync] (eval at create (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:13:28858), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:13:26012)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:130328
    at symbolIterator (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\neo-async\async.js:1:14402)
-- inner error --
Syntax error: C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css Unknown word (5:1)

  3 | @tailwind utilities;
  4 | 
> 5 | <<<<<<< HEAD
    | ^
  6 | /* body {
  7 |   height: 100%;

    at Object.<anonymous> (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[2]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[3]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css:1:7)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:922493
    at Hook.eval [as call] (eval at create (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:13:28636), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:13:25906)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131198
    at tryRunOrWebpackError (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:312943)
    at __webpack_require_module__ (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131165)
    at __nested_webpack_require_153728__ (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:130607)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131454
    at symbolIterator (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\neo-async\async.js:1:14444)

Generated code for C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[2]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[3]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css

Import trace for requested module:
./src/app/globals.css

> Build failed because of webpack errors
Error: Command "npm run build" exited with 1<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[2]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[3]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css': No serializer registered for PostCSSSyntaxError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> PostCSSSyntaxError
Failed to compile.

./src/app/globals.css:5:1
Syntax error: C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css Unknown word

  3 | @tailwind utilities;
  4 | 
> 5 | <<<<<<< HEAD
    | ^
  6 | /* body {
  7 |   height: 100%;

./src/app/globals.css
Syntax error: C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css Unknown word (5:1)

  3 | @tailwind utilities;
  4 | 
> 5 | <<<<<<< HEAD
    | ^
  6 | /* body {
  7 |   height: 100%;

    at tryRunOrWebpackError (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:312989)
    at __webpack_require_module__ (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131165)
    at __nested_webpack_require_153728__ (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:130607)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131454
    at symbolIterator (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\neo-async\async.js:1:14444)
    at done (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\neo-async\async.js:1:14824)
    at Hook.eval [as callAsync] (eval at create (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:13:28858), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:13:26012)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:130328
    at symbolIterator (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\neo-async\async.js:1:14402)
-- inner error --
Syntax error: C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css Unknown word (5:1)

  3 | @tailwind utilities;
  4 | 
> 5 | <<<<<<< HEAD
    | ^
  6 | /* body {
  7 |   height: 100%;

    at Object.<anonymous> (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[2]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[3]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css:1:7)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:922493
    at Hook.eval [as call] (eval at create (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:13:28636), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:13:25906)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131198
    at tryRunOrWebpackError (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:312943)
    at __webpack_require_module__ (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131165)
    at __nested_webpack_require_153728__ (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:130607)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131454
    at symbolIterator (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\neo-async\async.js:1:14444)

Generated code for C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[2]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[13].oneOf[12].use[3]!C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\globals.css

Import trace for requested module:
./src/app/globals.css

> Build failed because of webpack errors
Error: Command "npm run build" exited with 1

**Comment by yuseok-kim-edushare** [comment]
PS C:\Users\HP\Documents\GitHub\spharos5th-1st-front> vercel build
Vercel CLI 37.4.2
WARNING: You should not upload the `.next` directory.
Installing dependencies...

up to date in 3s

156 packages are looking for funding
  run `npm fund` for details
Detected Next.js version: 14.2.10
Running "npm run build"

> my-app@0.1.0 build
> next build

  ▲ Next.js 14.2.10
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully

./src/app/review/writeR/page.tsx
25:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./src/components/mainFilter/AllFilter.tsx
227:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./src/components/mainreview/review1/DummyData.tsx
38:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Linting and checking validity of types  ...Failed to compile.

.next/types/app/api/[category]/route.ts:2:24
Type error: File 'C:/Users/HP/Documents/GitHub/spharos5th-1st-front/my-app/src/app/api/[category]/route.ts' is not a module.

  1 | // File: C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\src\app\api\[category]\route.ts
> 2 | import * as entry from '../../../../../src/app/api/[category]/route.js'
    |                        ^
  3 | import type { NextRequest } from 'next/server.js'
  4 |
  5 | type TEntry = typeof import('../../../../../src/app/api/[category]/route.js')
Error: Command "npm run build" exited with 1

**Comment by yuseok-kim-edushare** [comment]
전부 주석 처리된 파일은 빌드 장애물이더라구요

**Comment by yuseok-kim-edushare** [comment]
WARNING: You should not upload the `.next` directory.
Installing dependencies...

up to date in 3s

156 packages are looking for funding
  run `npm fund` for details
Detected Next.js version: 14.2.10
Running "npm run build"

> my-app@0.1.0 build
> next build

  ▲ Next.js 14.2.10
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully

./src/app/review/writeR/page.tsx
25:13  Warning: Using `<img>` could result in slower LCP and higher banditional usage or cost from your provider. See: https://nextjs.org/docs

./src/components/mainFilter/AllFilter.tsx
227:15  Warning: Using `<img>` could result in slower LCP and higher badditional usage or cost from your provider. See: https://nextjs.org/doc

./src/components/mainreview/review1/DummyData.tsx
38:15  Warning: Using `<img>` could result in slower LCP and higher banditional usage or cost from your provider. See: https://nextjs.org/docs

info  - Need to disable some ESLint rules? Learn more here: https://nex
   Linting and checking validity of types  ..Failed to compile.

./src/components/maindelivery/DeliveryManagement.tsx:11:29y/DeliveryManagement.tsx:11: implicitly has an 'any' type.29
Type error: Parameter 'data' implicitly has an 'any' typn to update address data from the forme.                          mit = (data) => {
                                   ^
   9 |                      ta);
  10 |   // Callback functio

./src/components/maindelivery/DeliveryManagement.tsx:11:29
Type error: Parameter 'data' implicitly has an 'any' type.

   9 |
  10 |   // Callback function to update address data from the form
> 11 |   const handleFormSubmit = (data) => {
     |                             ^
  12 |     setAddressData(data);
  13 |   };
  14 |
Error: Command "npm run build" exited with 1

**Comment by yuseok-kim-edushare** [comment]
Vercel CLI 37.4.2
WARNING: You should not upload the `.next` directory.
Installing dependencies...

up to date in 3s

156 packages are looking for funding
  run `npm fund` for details
Detected Next.js version: 14.2.10
Running "npm run build"

> my-app@0.1.0 build
> next build

  ▲ Next.js 14.2.10
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully

./src/app/review/writeR/page.tsx
25:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./src/components/mainFilter/AllFilter.tsx
227:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./src/components/mainreview/review1/DummyData.tsx
38:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Linting and checking validity of types  ..Failed to compile.

./src/components/ui/button.tsx:2:22
Type error: Cannot find module '@radix-ui/react-slot' or its corresponding type declarations.

  1 | import * as React from "react"
> 2 | import { Slot } from "@radix-ui/react-slot"
    |                      ^
  3 | import { cva, type VariantProps } from "class-variance-authority"
  4 |
  5 | import { cn } from "@/lib/utils"

**Comment by yuseok-kim-edushare** [comment]
✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/25)  [=   ]Error: Event handlers cannot be passed to Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:150268)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '3999825366'
}
Error: Event handlers cannot be passed to Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135346)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '2659799892'
}
Error: Event handlers cannot be passed to Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135346)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '2659799892'
}
 ⚠ Sending SIGTERM signal to static worker due to timeout of 60 seconds. Subsequent 
errors may be a result of the worker exiting.
 ⚠ Restarted static page generation for /delivery/newdelivery because it took more than 60 seconds
 ⚠ See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
   Generating static pages (24/25)  [=== ]Error: Event handlers cannot be passed to 
Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:150268)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '3999825366'
}
Error: Event handlers cannot be passed to Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135346)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '2659799892'
}
Error: Event handlers cannot be passed to Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135346)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '2659799892'
}
 ⚠ Sending SIGTERM signal to static worker due to timeout of 60 seconds. Subsequent 
errors may be a result of the worker exiting.
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⚠ Restarted static page generation for /delivery/newdelivery because it took more than 60 seconds
   Generating static pages (24/25)  [=== ]Error: Event handlers cannot be passed to 
Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:150268)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '3999825366'
}
Error: Event handlers cannot be passed to Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135346)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '2659799892'
}
Error: Event handlers cannot be passed to Client Component props.
  {onSubmit: function onSubmit, children: ...}
             ^^^^^^^^^^^^^^^^^
If you need interactivity, consider converting part of this to a Client Component.  
    at ek (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:140437)
    at Object.toJSON (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135626)
    at stringify (<anonymous>)
    at eR (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142090)
    at eE (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142569)
    at Timeout._onTimeout (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135346)     
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  digest: '2659799892'
}
 ⚠ Sending SIGTERM signal to static worker due to timeout of 60 seconds. Subsequent 
errors may be a result of the worker exiting.
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM
 ⨯ Static worker exited with code: null and signal: SIGTERM

> Build error occurred
Error: Static page generation for /delivery/newdelivery is still timing out after 3 
attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
    at onRestart (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\build\index.js:279:27)
    at C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\lib\worker.js:95:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)   
    at async C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\export\index.js:450:20
    at async Span.traceAsyncFn (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\trace\trace.js:154:20)
    at async C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\export\index.js:448:24
    at async Promise.all (index 8)
    at async exportAppImpl (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\export\index.js:440:21)
    at async C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\export\index.js:623:16
    at async Span.traceAsyncFn (C:\Users\HP\Documents\GitHub\spharos5th-1st-front\my-app\node_modules\next\dist\trace\trace.js:154:20)
   Generating static pages (24/25)  [    ]Error: Command "npm run build" exited with 1

**Comment by yuseok-kim-edushare** [comment]
![image](https://github.com/user-attachments/assets/00846c0c-cbe9-43f4-a6ef-ab1e052cff78)
Error from split of package.json in My-app (root directory of next.js project) and in Git repository root

**Comment by yuseok-kim-edushare** [comment]
![image](https://github.com/user-attachments/assets/0c4edd8c-c27d-4761-a934-cc18f020b70a)
